name: CI

on:
  - push
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.6.1
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.7'
      - name: Install Package and its Dependencies
        run: raco pkg install --auto --skip-installed seq algorithms binary-class rack-unit
      - name: Run Tests
        run: raco test .
