name: CI

on:
  - push
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.16'
      - name: Install Package and its Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lilypond
      - name: Run Tests
        run: |
          export LILYPOND_VERSION=2.22
          mkdir ./lib/test
          cp ./adjust-expression.ly ./lib/test
          mkdir ./ws/test
          cp ./adjust-expression.ly ./ws/test
          raco pkg install --auto --no-docs
          raco test .
