name: CI

on:
  - push
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.7'
      - name: Run Tests
        run: |
          export LILYPOND_VERSION=2.22
          mkdir ./lib/test
          raco test .
